server:
  port: 8082

spring:
  application:
    name: orderflow-events
  datasource:
    url: jdbc:postgresql://localhost:5433/orderflow
    username: orderflow
    password: orderflow
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
